### ISSUE TITLE
Chromium package suggest

### ISSUE THREAD

**Issue by Escxtt23** [termux/unstable-packages#128] opened 2019-09-24 12:31 UTC

**Comment by RossComputerPerson** [comment] 2019-09-24 13:23
Browsers like chrome will not be added as they are too much.

**Comment by xeffyr** [comment] 2019-09-24 15:31
Duplicate of https://github.com/termux/termux-packages/issues/910 + yes, it is unlikely that chrome will be available in near future.

**Closed by xeffyr** 2019-09-24 15:31 UTC
